# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-29 00:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190128_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='detail'),
        ),
    ]
